### ISSUE TITLE
‘macOS could not be installed on your computer’ error 

### ISSUE THREAD

**Issue by CharlesCCC** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#1]
I'm trying to install the moJava in R7, i have exactly the same specs as you do. 
but when I using uniBeast to install the OS, it gave me the error Can you please share some insight, thank you.

**Comment by jianghaizhi** [comment]
You can first use clover configuration to update the EFI/clover in your USB to latest version, then try to install MacOS. The default EFI/clover version created by UniBeast is a bit old.

**Comment by CharlesCCC** [comment]
thank you for the suggestion, I have tried using the latest clover `Clover_v2.4k_r4586-UEFI`

but I can't even get to the install screen anymore, it getting me this error 
`ACPI Error: 9 table load failures, 4 successful`

**Comment by CharlesCCC** [comment]
It all set, after I install the `Clover_v2.4k_r4784` with copy paste all of your EFI files. 
but one thing wasn't sure, the Audio device is not set.

**Comment by jianghaizhi** [comment]
Try to plug in your audio device to the centre connector in the second row and select Internal speakers in System Preferences>Sound

**Comment by CharlesCCC** [comment]
@jianghaizhi thank you very much for the kind help, really appreciated. 
btw,  for the wireless card, I do have a Airport card + PCi-E adapter that I can use, the only downside is, the R7 motherboard doesn't come with the standard USB header, which is required to enable the bluetooth for the Airport card in Hackintosh build.

**Comment by CharlesCCC** [comment]
@jianghaizhi Just a update with the wireless card, I was able to get it to work by some hacking around. Basically, I cut off a old usb cable and used it connect to the adapter, then I was able to use external usb connection to get the wireless card to work perfectly (wife+bluetooth) with Airdrop, Airplay etc. worked perfectly.

**Comment by jianghaizhi** [comment]
> @jianghaizhi Just a update with the wireless card, I was able to get it to work by some hacking around. Basically, I cut off a old usb cable and used it connect to the adapter, then I was able to use external usb connection to get the wireless card to work perfectly (wife+bluetooth) with Airdrop, Airplay etc. worked perfectly.

Which card do you use? 
I bought a DW1830 and replaced the original card by it in the M.2 interface on motherboard.
The wifi works OOB, BrcmPatchRAM2.kext and BrcmFirmwareRepo.kext are added to /L/E to enable BT.    
In the meantime, I inject the port used for M.2 interface for BT in USBinjectALL.kext as  **internal**. It works so far so good.

**Comment by CharlesCCC** [comment]
@jianghaizhi  that's great to know, I bought the Airport BCM4360 card(used by actual Macs) and insert it into a PCI-e adapter.  the Adapter is using PCI-e x4 interface with additional USB connection required for the bluetooth to work.  (No Kext/Patches required for either of to work, as long as get all the connection to work).  The only downside about this approach is what I mentioned earlier, the R7 doesn't come with additional USB header, so I have stick the wire out and connect the internal PCI-e USB to the external USB port (not too bad consider it is on the back of the case).
