### ISSUE TITLE
Ethernet?

### ISSUE THREAD

**Issue by ghost** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#10]
Do I need to change my network card which is E2500, because I do not need wireless connection?(I know 1535 broke down)
Also, is this EFI for GTX1080 or RX580?
thx

**Comment by jianghaizhi** [comment]
I think the default ethernet card can work in hackintosh. 

The graphics card should be RX580. Apple supports AMD graphics cards in new versions MacOS, while Nvidia cards can only work in old versions (older than high serria)

**Comment by ghost** [comment]
So in this repo \High-Serria-10.13.6 these EFI files are for GTX 1080 on Aurora R7, right?
Thx a lot 😄 😄

**Comment by jianghaizhi** [comment]
Yes, you can use /High-Serria-10.13.6

**Comment by ghost** [comment]
Thx a lot!
