### ISSUE TITLE
Windows to Mac 

### ISSUE THREAD

**Issue by rephiled** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#11]

**Comment by rephiled** [comment]
I am selling my Aurora 7 it has a Windows OS I was asked to put on a Mac OS what is need to do that and make it boot to Mac and not Windows

**Comment by jianghaizhi** [comment]
I do not have dual systems in my computer. I think there are some tutorials posted, you can google to find them.

**Comment by jianghaizhi** [comment]
close
