### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by Arshavink** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#13]
Hi there, 
I'm trying to install mac os mojave on my alienware r8 but its not booting properly form clover, after the apple logo I am getting an error logo and that's it, if you can help me fix it 

thanks

**Comment by jianghaizhi** [comment]
You can try to use a USB2 port to install. Does your machine have USB2 ports?

**Comment by Arshavink** [comment]
only usb3

**Comment by Arshavink** [comment]
now it's working but my gtx 1050ti not working and intel 630 too, can you help me with my troubleshooting 

thanks

**Comment by jianghaizhi** [comment]
Mojave does not support NVIDIA card. If you want to use it, you can try to install an older version of MacOS. Intel 630 should work under Mojave.
