### ISSUE TITLE
considerRebuildOfPrelinkedKernel

### ISSUE THREAD

**Issue by KP2048** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#19]
I installed macOS, but when I try to boot it, it gets stuck at considerRebuildOfPrelinkedKernel

**Comment by CryptoNeverSleeps** [comment]
https://github.com/CryptoNeverSleeps/DELL-Alienware-Aurora-R7-macOS

I also published the Open Core Files for my build here... (Clover Updated Files above *Tested on 10.15.3)


Tested on 10.15.4....

https://github.com/CryptoNeverSleeps/Alienware-Aurora-R7-Open-Core

**Comment by KP2048** [comment]
thanks ill try it

**Comment by KP2048** [comment]
Still happening

**Comment by KP2048** [comment]
![image](https://user-images.githubusercontent.com/39203202/77834804-6884b180-7115-11ea-9e0c-95846177fe7a.jpg)

**Comment by KP2048** [comment]
It gets stuck here

**Comment by CryptoNeverSleeps** [comment]
What Graphics card are you using...
and custom boot flags?

Consider using Open Core....

**Comment by CryptoNeverSleeps** [comment]
My Open Core Build is 100% working
 Type C Port as well...

**Comment by KP2048** [comment]
Nvidia gtx 1050 ti

**Comment by KP2048** [comment]
i dont have a display port cable and my monitor only supports hdmi so I can't use integrated graphics because it only has display port

**Comment by KP2048** [comment]
in the plist is the boot flags under root->boot->arguments ?
i don't currently have access to the Alienware that I'm installing Catalina on but I have access to my mom's MacBook air that I made the installation USB on.

**Comment by KP2048** [comment]
the value in that key of the list is:
dart=0 keepsyms=1 -disablegfxfirmware
