### ISSUE TITLE
Internal Sound device disappeared after 10.4.2 update

### ISSUE THREAD

**Issue by CharlesCCC** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#2]
Internal Sound device disappeared after 10.4.2 update 

@jianghaizhi Did you updated to 10.4.2 ?

**Comment by jianghaizhi** [comment]
You can try to set: Clover settings -> Devices  -> Audio -> Inject 2.

Yes, I have updated to 10.14.2 with no problem.

**Comment by CharlesCCC** [comment]
uhh, didn't work. No device showing at all. tried both inject 1&2

**Comment by jianghaizhi** [comment]
Try update AppleALC in /S/E, and refresh kext cache.
https://github.com/acidanthera/AppleALC

**Comment by CharlesCCC** [comment]
@jianghaizhi tried that yesterday, when I ran the command `sudo kextcache -i` the system gave me a error saying something like `kext with invalid signature (-67062) allowed`

**Comment by CharlesCCC** [comment]
Was able to resolve the issue after place the latest version of APPALC to the /S/L/E/ instead of the /S/E/
both the front 3.5mm and back 3.5mm audio port are working perfectly. thank you.
