### ISSUE TITLE
Booting stops at AppleUserUSBHostHIDDevice: force close

### ISSUE THREAD

**Issue by Jarxi** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#20]
I am using Aurora r8 with internal graphics. Connecting to a monitor with DP.

**Comment by Jarxi** [comment]
I paste all of your EFI files into my EFI folder

**Comment by Jarxi** [comment]
https://drive.google.com/file/d/1ak3nqeavgv8sLh06bovyKx_1_BeX8MRy/view?usp=sharing
找不到解决办法 只好来问问你了
拜托了

**Comment by jianghaizhi** [comment]
你的安装u盘是插到usb2接口了吗？

**Comment by Jarxi** [comment]
> 你的安装u盘是插到usb2接口了吗？

我查了一下，中间蓝色的是3.0 黑色的2.0，我两个都试过了 都是在同一个地方停住了

**Comment by jianghaizhi** [comment]
正确的是应该插在USB2. 我估计你的问题可能和macos的版本有关，我刚才更新了一下，所有的driver和kext还有clover都更新到最新版本了，你试试看更新一下能不能成功

**Comment by Jarxi** [comment]
好 我试一下 是在install之前先替换你的files吗 还是install之后

**Comment by Jarxi** [comment]
恩 不太行 现在是 igpu 一直在retry  可能是gpu有关系

**Comment by Jefferson88faj** [comment]
hello please, could you specify how is your bios configuration, I think I did something wrong and now I can't enter setup or boot. but I'll see how to fix that, but help me with the bios configuration.

**Comment by jianghaizhi** [comment]
> hello please, could you specify how is your bios configuration, I think I did something wrong and now I can't enter setup or boot. but I'll see how to fix that, but help me with the bios configuration.

My BIOS setting is the same as this:
https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/
