### ISSUE TITLE
Wake Up issue

### ISSUE THREAD

**Issue by CharlesCCC** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#3]
Hi @jianghaizhi , Sorry to bother you again. 
but after using mine for couple days, I have noticed two issues related with Wake-up from sleep:

1. whenever wake up from sleep, the video playback function will break, e.g. can't play any video, can't view live-photo. have to reboot to fix it; (I'm using MSI RX 580 8G Video card) 
2. whenever it went to sleep, the USB will be shut-off disconnect, I have attached an external USB drive to use as Timemachine for backup, evertime after I wake up the Hackintosh, I will see tons of pop-up saying the USB device "Disk Not Ejected Properly". 

I just wondering if you have experienced similar issue or not, if yes, I would love to hear what did you do to fix it. thank you very much.

**Comment by jianghaizhi** [comment]
I have no issue related to sleep/wakeup. I use an external usb drive for TM backup too, but have no problem. Do you include my SSDT-UIAC.aml in config.plist?

What do you mean for 'playback' a video? I use a Gigabyte Aorus RX 580, it works OOB. I do not see any problem for video playing (for both online and downloaded videos) after wakeup.

**Comment by jianghaizhi** [comment]
Which usb port your are using for connecting the usb drive?

**Comment by CharlesCCC** [comment]
@jianghaizhi for video playback, I meant any video, mp4 youtube live-photo, anything involved with play video file will stop working after wakeup. 

As for the `SSDT-UIAC.ami`, I didn't change anything in the config.plist besides the SMBIOS (Serial number etc.)

for you references, here is mine:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ACPI</key>
	<dict>
		<key>DSDT</key>
		<dict>
			<key>Debug</key>
			<false/>
			<key>DropOEM_DSM</key>
			<false/>
			<key>Fixes</key>
			<dict>
				<key>FiX_TMR_40000</key>
				<false/>
				<key>FiX_WAK_200000</key>
				<false/>
				<key>FixMutex</key>
				<true/>
				<key>FixSATA</key>
				<true/>
				<key>FixShutdown</key>
				<true/>
			</dict>
			<key>Name</key>
			<string>DSDT.aml</string>
			<key>Patches</key>
			<array>
				<dict>
					<key>Comment</key>
					<string>change EHC1 to EH01</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					RUhDMQ==
					</data>
					<key>Replace</key>
					<data>
					RUgwMQ==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change EHC2 to EH02</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					RUhDMg==
					</data>
					<key>Replace</key>
					<data>
					RUgwMg==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change XHCI to XHC</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					WEhDMQ==
					</data>
					<key>Replace</key>
					<data>
					WEhDXw==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change GFX0 to IGPU</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					R0ZYMA==
					</data>
					<key>Replace</key>
					<data>
					SUdQVQ==
					</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>change SAT0 to SATA</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					U0FUMA==
					</data>
					<key>Replace</key>
					<data>
					U0FUQQ==
					</data>
				</dict>
			</array>
			<key>ReuseFFFF</key>
			<false/>
		</dict>
		<key>DropTables</key>
		<array>
			<dict>
				<key>Signature</key>
				<string>MATS</string>
			</dict>
			<dict>
				<key>Signature</key>
				<string>DMAR</string>
			</dict>
			<dict>
				<key>Signature</key>
				<string>SSDT</string>
				<key>TableId</key>
				<string>UIAC</string>
			</dict>
		</array>
		<key>FixHeaders</key>
		<true/>
		<key>SSDT</key>
		<dict>
			<key>DropOem</key>
			<false/>
			<key>Generate</key>
			<dict>
				<key>CStates</key>
				<false/>
				<key>PStates</key>
				<false/>
			</dict>
		</dict>
		<key>SortedOrder</key>
		<array>
			<string>SSDT-UIAC.aml</string>
		</array>
	</dict>
	<key>Boot</key>
	<dict>
		<key>Arguments</key>
		<string>-disablegfxfirmware</string>
		<key>Debug</key>
		<true/>
		<key>DefaultVolume</key>
		<string>SSD</string>
		<key>Legacy</key>
		<string>PBR</string>
		<key>Log</key>
		<true/>
		<key>Secure</key>
		<false/>
		<key>Timeout</key>
		<integer>3</integer>
		<key>XMPDetection</key>
		<false/>
	</dict>
	<key>Devices</key>
	<dict>
		<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>2</integer>
			<key>ResetHDA</key>
			<true/>
		</dict>
		<key>FakeID</key>
		<dict>
			<key>ATI</key>
			<string>0x0</string>
			<key>IMEI</key>
			<string>0x0</string>
			<key>IntelGFX</key>
			<string>0x00</string>
			<key>LAN</key>
			<string>0x0</string>
			<key>NVidia</key>
			<string>0x0</string>
			<key>SATA</key>
			<string>0x0</string>
			<key>WIFI</key>
			<string>0x0</string>
			<key>XHCI</key>
			<string>0x0</string>
		</dict>
		<key>USB</key>
		<dict>
			<key>FixOwnership</key>
			<true/>
			<key>Inject</key>
			<true/>
		</dict>
	</dict>
	<key>DisableDrivers</key>
	<array>
		<string>Nothing</string>
	</array>
	<key>GUI</key>
	<dict>
		<key>Hide</key>
		<array>
			<string>\EFI\BOOT\BOOTX64.EFI</string>
			<string>BOOTX64.EFI</string>
			<string>recovery</string>
			<string>preboot</string>
		</array>
		<key>Language</key>
		<string>en:0</string>
		<key>Mouse</key>
		<dict>
			<key>Enabled</key>
			<true/>
			<key>Speed</key>
			<integer>8</integer>
		</dict>
		<key>Scan</key>
		<dict>
			<key>Entries</key>
			<true/>
			<key>Legacy</key>
			<false/>
			<key>Linux</key>
			<false/>
			<key>Tool</key>
			<false/>
		</dict>
		<key>ScreenResolution</key>
		<string>1920x1080</string>
		<key>Theme</key>
		<string>Bootcamp4k</string>
	</dict>
	<key>Graphics</key>
	<dict>
		<key>Inject</key>
		<dict>
			<key>ATI</key>
			<false/>
			<key>Intel</key>
			<true/>
			<key>NVidia</key>
			<false/>
		</dict>
	</dict>
	<key>KernelAndKextPatches</key>
	<dict>
		<key>#FakeCPUID</key>
		<string>0x010676</string>
		<key>AppleIntelCPUPM</key>
		<true/>
		<key>AppleRTC</key>
		<true/>
		<key>KernelCpu</key>
		<false/>
		<key>KernelLapic</key>
		<false/>
		<key>KernelPm</key>
		<true/>
		<key>KernelXCPM</key>
		<false/>
		<key>KextsToPatch</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>External icons patch</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				RXh0ZXJuYWw=
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>AppleAHCIPort</string>
				<key>Replace</key>
				<data>
				SW50ZXJuYWw=
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>USB Port limit patch 10.14.1</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				g/sPD4OPBAAA
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>com.apple.driver.usb.AppleUSBXHCI</string>
				<key>Replace</key>
				<data>
				g/sPkJCQkJCQ
				</data>
			</dict>
		</array>
	</dict>
	<key>RtVariables</key>
	<dict>
		<key>BooterConfig</key>
		<string>0x28</string>
		<key>CsrActiveConfig</key>
		<string>0x67</string>
		<key>ROM</key>
		<data>
		yU4M3llo
		</data>
	</dict>
	<key>SMBIOS</key>
	<dict>
		<key>BiosReleaseDate</key>
		<string>09/17/2018</string>
		<key>BiosVendor</key>
		<string>Apple Inc.</string>
		<key>BiosVersion</key>
		<string>MM81.88Z.F000.B00.1809171422</string>
		<key>Board-ID</key>
		<string>Mac-7BA5B2DFE22DDD8C</string>
		<key>BoardManufacturer</key>
		<string>Apple Inc.</string>
		<key>BoardSerialNumber</key>
		<string>C07805501GUUE</string>
		<key>BoardType</key>
		<integer>10</integer>
		<key>BoardVersion</key>
		<string>1.0</string>
		<key>ChassisAssetTag</key>
		<string>Mini-Aluminum</string>
		<key>ChassisManufacturer</key>
		<string>Apple Inc.</string>
		<key>ChassisType</key>
		<string>0x09</string>
		<key>EfiVersion</key>
		<string>220.207.27.0.0</string>
		<key>Family</key>
		<string>Mac mini</string>
		<key>FirmwareFeatures</key>
		<string>0xFC0FE137</string>
		<key>FirmwareFeaturesMask</key>
		<string>0xFF1FFF3F</string>
		<key>LocationInChassis</key>
		<string>Part Component</string>
		<key>Manufacturer</key>
		<string>Apple Inc.</string>
		<key>Mobile</key>
		<false/>
		<key>PlatformFeature</key>
		<string>0x02</string>
		<key>ProductName</key>
		<string>Macmini8,1</string>
		<key>SerialNumber</key>
		<string>C07W6JZEJYVX</string>
		<key>SmUUID</key>
		<string>5D86278F-BFD5-4DDC-A31B-9AE1F63E371A</string>
		<key>Version</key>
		<string>1.0</string>
	</dict>
	<key>SystemParameters</key>
	<dict>
		<key>CustomUUID</key>
		<string>AC8D14D5-A0A2-5888-9C8B-33788ABB699D</string>
		<key>InjectKexts</key>
		<string>Detect</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>
</dict>
</plist>
```


i'm using the USB3.0 port from the back.

**Comment by jianghaizhi** [comment]
I have update the config file, please try the new one in DELL-Alienware-Aurora-R7-macOS/EFI/CLOVER/config.plist. This may fix your sleep/wakeup problem.

For the USB problem, please not plug to the first one from left of the 4 usb3 ports in the back. 
The 15 port limit patch does not work for Mojave, therefore only less than 15 port are inject through SSDT. These injected ports include all the four port in the front, the four usb2 ports in the second line in the back, and the 3 usb3 ports (except the first one from left) in the back.

The first one from left usb3 port in the back is indeed a usb 3.1 port, and controlled by a usb hub. other usb3 ports are controlled by the motherboard.

You may also need to update usbinjectall.kext to the newest version and refresh kext cache.

**Comment by CharlesCCC** [comment]
![screen shot 2018-12-20 at 5 36 37 pm](https://user-images.githubusercontent.com/7534809/50314692-d9064280-047d-11e9-8200-68f85efc2bcf.png)

This is waht i'm talking about regarding to the disconnecting USB after wake up.

**Comment by jianghaizhi** [comment]
> I have update the config file, please try the new one in DELL-Alienware-Aurora-R7-macOS/EFI/CLOVER/config.plist. This may fix your sleep/wakeup problem.
> 
> For the USB problem, please not plug to the first one from left of the 4 usb3 ports in the back.
> The 15 port limit patch does not work for Mojave, therefore only less than 15 port are inject through SSDT. These injected ports include all the four port in the front, the four usb2 ports in the second line in the back, and the 3 usb3 ports (except the first one from left) in the back.
> 
> The first one from left usb3 port in the back is indeed a usb 3.1 port, and controlled by a usb hub. other usb3 ports are controlled by the motherboard.
> 
> You may also need to update usbinjectall.kext to the newest version and refresh kext cache.

did you try this? does it work?

**Comment by CharlesCCC** [comment]
@jianghaizhi thank you for the suggestion:

1, I cherry pick your change from the config.plist (didn't apply the bluetooth/handoff because I don't need it, consider I'm using the Airport card).  but unfortunately after the wakeup, the video playback still not waking. 

2, as for the USB3, I definitely plugged my hard-driver(TimeMachine) into the 1st of the four USB3 port, I will move it to another.   but this is really confused me tho, based on what you said, if it only 15, then the 1st port shouldn't work at all, but it only works when the computer are awake and disconnected after the computer went to sleep.

**Comment by jianghaizhi** [comment]
1, Do you add the kexts of Lilu and whatevergreen?

2, The first port is integrated by a 3rd party hub, it is a little difficult to control it. I am not very clear about it, that is why I do not inject that port.

**Comment by CharlesCCC** [comment]
1, I saw Lilu.kext in /L/E   didn't see  `whatevergree` in anyplace, neither do i know what is for. 

2, gotcha. 

thank you.

**Comment by jianghaizhi** [comment]
whatevergreen.kext is a video related drive, try put it in the same folder with Lilu, remember refreshing cache

**Comment by CharlesCCC** [comment]
@jianghaizhi You are right, the `whatevergree.kext` did the trick. I updated it along with `lilu.kext`, now the issue seems fixed, the video playback works perfect without any issue.  should both kext been put inside your repo `https://github.com/jianghaizhi/DELL-Alienware-Aurora-R7-macOS/tree/master/EFI/CLOVER/kexts/Other` ?

**Comment by jianghaizhi** [comment]
> @jianghaizhi You are right, the `whatevergree.kext` did the trick. I updated it along with `lilu.kext`, now the issue seems fixed, the video playback works perfect without any issue. should both kext been put inside your repo `https://github.com/jianghaizhi/DELL-Alienware-Aurora-R7-macOS/tree/master/EFI/CLOVER/kexts/Other` ?

Thank you for your reminder, I will update it later. I am really busy these days -.-.
