### ISSUE TITLE
USB Timemachine kee disconnectin again after latest upgrade and USB change

### ISSUE THREAD

**Issue by CharlesCCC** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#6]
Similar to issue #3  

Recently I just upgrade to OS 10.14.3 and then also applied the following change
```
Comment: USB port limit patch 10.14.1 10.14.2 (credit ydeng).
Name: IOUSBHostFamily
Find: 00e0 83fb 0f0f 8716 0400
Replace: 00e0 83fb 3f0f 8716 0400

Comment: USB Port limit patch 10.14.1, 10.14.2.
Name: com.apple.driver.usb.AppleUSBXHCI
Find: 00 00 83 FB 0F 0F 83 8F 04 00 00
Replace: 00 00 83 FB 3F 0F 83 8F 04 00 00
```

The TimeMachine USB drive keep disconnecting again while my Hackintosh at sleep :( 
FYI, my drive is still plugged in the 2nd USB3 port from the back.

**Comment by jianghaizhi** [comment]
Do you remove the usb-related SSDT patch in config file?

**Comment by CharlesCCC** [comment]
Are you reference this part of code ? https://github.com/jianghaizhi/DELL-Alienware-Aurora-R7-macOS/blob/571720a06cfd062dd76151835faa9f6e3142562c/EFI/CLOVER/config.plist#L151-L170 

If yes, then my answer is no, I didn't remove anything from the config file, but updated it with the new value you provided.

**Comment by jianghaizhi** [comment]
Please try to remove SSDT-UIAC.aml in SortedOrder

**Comment by CharlesCCC** [comment]
Thank you for the suggestion, 
I deleted the following yesterday 
```
 <key>SortedOrder</key> 
 <array> 
 	<string>SSDT-UIAC.aml</string> 
 </array> 
``` 
, but this morning when i wake up my computer, I still seems the warning messages.

**Comment by jianghaizhi** [comment]
Maybe there is still some problem for the 15 port limit patch. You can continue to use the customized ssdt patch if it works.

**Comment by jianghaizhi** [comment]
BTW, I have upload all the kexts in my machine to /EFI/CLOVER/kexts/Other/, you can check them and add to you EFI.

**Comment by CharlesCCC** [comment]
Thank you for the reply, so I went back with the SSDT path you provided, here is my current config.plist related to USB (which is identical to yours as far as I can tell):

```
line 167 - 170 
		<key>SortedOrder</key>
		<array>
			<string>SSDT-UIAC.aml</string>
		</array>
```

```
line 315 - 332
			<dict>
				<key>Comment</key>
				<string>USB Port limit patch 10.14.1, 10.14.2</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				g/sPD4OPBAAA
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>com.apple.driver.usb.AppleUSBXHCI</string>
				<key>Replace</key>
				<data>
				g/sPkJCQkJCQ
				</data>
			</dict>
```

In addition, I have moved all of the Kexts from `Other` folder to the `/Library/Extensions/` folder. 

but unfortunately the issue still persist.  the TimeMachine external USB driver will be ejected every time when the Hackintosh went to sleep :(

**Comment by CharlesCCC** [comment]
Ps, I just tried update my clove to latest version(r4871), we will see if that make any difference.

**Comment by CharlesCCC** [comment]
well, update Clover didn't help... and now I'm getting back to an old issue which is taking a long time to wake up from sleep :(

**Comment by jianghaizhi** [comment]
My machine seems do not have this problem. Maybe this problem is related to UEFI drivers, I will update the drivers in these days.

**Comment by CharlesCCC** [comment]
thank you... 

Did couple more research in tonymac86, there are two potential causes
1, XMP caused the issue
2, USB injection 

The 1st doesn't make too much sense to me, because my XMP never changed,it is default R7. which was working fine before. 

The 2nd didn't apply to my case neither, because I reverted the change to exactly the same config to use SSMT-aiac again. 

I'm wondering if the BIOS Power setting or the new Config about mac default power setting have made any different.

**Comment by jianghaizhi** [comment]
I have committed a new version with latest kexts and UEFI drivers. You can try if it can fix your issue.

**Comment by CharlesCCC** [comment]
@jianghaizhi thank you very much. I believe the issue has been fixed. 
Another thing I have noticed is that I need to disable "standby" mode from the `pmset` setting.

```
sudo pmset -a hibernatemode 0
sudo pmset -a standby 0
sudo pmset -a standbydelay 8640000
sudo pmset -a autopoweroff 0
```

**Comment by jianghaizhi** [comment]
Thank you for your infomation
