### ISSUE TITLE
audio not stable

### ISSUE THREAD

**Issue by CharlesCCC** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#7]
Howdy,

Have you updated to 10.14.4 ?  after update, I have issue with audio. It not stable, basiclly, the audio will come and go randomly.  

Note: I also have updated to latest Clover, AppleALC, Lilu, Whatevergreen.

**Comment by jianghaizhi** [comment]
Yes, I have tried to update to 10.14.4 several days ago, there is no audio issue. 
Do you inject 1 in config.plist/Devices/Audio? You can use clover configurator app to manage config.plist.

I connect two 4k monitors to my RX 580, and I find the GPU in 10.14.4 runs much hotter than 10.14.3 and the GPU fans spin very loudly (around 800 rpm in 10.14.3, around 1800 rpm in 10.14.4). So I return to 10.14.3.

**Comment by CharlesCCC** [comment]
It was 
```
		<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>2</integer>
			<key>ResetHDA</key>
			<true/>
		</dict>
```

I just changed it to 1 as you instructed. 

Which Rx580 do you have ? i'm not seeing the problem. (I have the MSI Armor II RX580). It running like normal, no-noticeable heat or super noise fan.  Have you updated to latest Whatevergreen and Lilu as well ?

**Comment by CharlesCCC** [comment]
change the Inject from 2 to 1 seems helped a little bit, but still having issue. Then after couple more research, It seems like 
remove those two lines helped: (not needed I guess?) 
https://github.com/jianghaizhi/DELL-Alienware-Aurora-R7-macOS/blob/master/EFI/CLOVER/config.plist#L197-L198 

```
			<key>ResetHDA</key>
			<true/>
```

**Comment by jianghaizhi** [comment]
My card is Sapphire Radeon NITRO+ RX 580. I guess the reasons it runs hot are: 1, I connect two 4k monitors; 2, the BIOS of AMD card is coarse; 3, the GPU works more exhaustively in 10.14.4.

It seems the iGPU can now work good (no kernel panic) in 10.14.4 with the newest version of whatevergreen. You can try to enable iGPU to see if there is still audio issue.

**Comment by jianghaizhi** [comment]
I guess these two lines will not influence the performance of the audio devices, because my machine runs good with them. 
```
<key>ResetHDA</key>
			<true/>
```

Is your speaker connected to the centre port in the second line?

**Comment by CharlesCCC** [comment]
@jianghaizhi yes, looks like it is stable now. Not sure what was going on. Maybe it is due to iGPU, I re-enabled it last night, everything fine today. Thank you.
