### ISSUE TITLE
Can you control the fan speed?

### ISSUE THREAD

**Issue by YihangFu** [jianghaizhi/DELL-Alienware-Aurora-R7-macOS#9]
Sorry for disturbing. Are you using liquid cooling? The default fan speed of liquid cooler on my Aurora R6 is about 1600rpm and I think the noise is too loud. Do you have this problem on your Aurora? thank you.

**Comment by jianghaizhi** [comment]
Both the default case fans and PSU fan are very loud in Aurora. You can change them by yourself. 

suggestion 1: change the top to ML120 PRO, this fan can pass the DELL system check. While a lot of other fans can not pass the DELL system check. Note that, the RGB version of ML120 PRO can not pass the check too, please select other color versions. This fan is very quiet.

suggestion 2: you can change the front fan to any silent fan.

suggestion 3: replace the PSU to a better brand PSU, > 500w, with smart fan control. Or change the PSU fan.

**Comment by YihangFu** [comment]
Thank you so much! These are really helpful.
